DROP TABLE IF EXISTS User;

CREATE TABLE IF NOT EXISTS User (
    id_user INTEGER PRIMARY KEY AUTOINCREMENT,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    affiliate_status INTEGER,
    referral_code VARCHAR(100)
);